name: Scrape and Save Page
on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL to scrape'
        required: true
        type: string

jobs:
  scrape-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4 asyncio
          playwright install firefox
          playwright install-deps firefox

      - name: Prepare URL patterns file
        run: |
          touch url_patterns.json
          [ -s url_patterns.json ] || echo "{}" > url_patterns.json

      - name: Scrape and save page
        env:
          TARGET_URL: ${{ github.event.inputs.target_url }}
        run: |
          python scraper.py "$TARGET_URL"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          mkdir -p sites
          git add -f url_patterns.json sites/
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Scrape: ${{ github.event.inputs.target_url }}"
            git push
          fi
