name: Scrape and Save Page
on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL to scrape'
        required: true
        type: string

jobs:
  scrape-page:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 明示的なバージョン指定
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgbm-dev \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libgbm1 \
            libasound2 \
            libpango-1.0-0 \
            libpangocairo-1.0-0

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4 asyncio
          playwright install firefox --with-deps
          playwright install-deps firefox

      - name: Prepare URL patterns file
        run: |
          touch url_patterns.json
          [ -s url_patterns.json ] || echo "{}" > url_patterns.json

      - name: Scrape and save page
        env:
          TARGET_URL: ${{ github.event.inputs.target_url }}
          PYTHONUNBUFFERED: "1"
        run: |
          python scraper.py "$TARGET_URL"

      - name: Commit and push changes
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          mkdir -p sites
          git add -f url_patterns.json sites/
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Scrape: ${{ github.event.inputs.target_url }}"
            git push
          fi
