name: Run Proxy Server

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL to proxy'
        required: true
        type: string
      port:
        description: 'Port number for the proxy server'
        required: false
        default: '8000'
        type: string

jobs:
  run-proxy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn aiohttp beautifulsoup4

      - name: Run proxy server
        run: |
          # Start the proxy server
          python proxy_server.py --port ${{ github.event.inputs.port }} &
          
          # Wait for server to start
          sleep 5
          
          # Set initial target URL
          curl "http://localhost:${{ github.event.inputs.port }}/set-target?url=${{ github.event.inputs.target_url }}"
          
          # Display server information
          echo "Proxy server is running on port ${{ github.event.inputs.port }}"
          echo "Target URL: ${{ github.event.inputs.target_url }}"
          
          # Keep the action running
          while true; do
            echo "Server is running... ($(date))"
            echo "Access via: http://localhost:${{ github.event.inputs.port }}"
            echo "Press Cancel workflow to stop."
            sleep 60
          done
